<?php
//-------------------------------------------------------------
// show different kinds of data based on the requested page
//-------------------------------------------------------------







function profile_cle() {
$content = <<<EOF
<p>
Looking for your CLE Summary? Contact Alene Sybrant, <a href="mailto:asubrant@ocdla.org">asybrant@ocdla.org</a>, to request a copy.
</p>
EOF;

	return $content;
}