<?php


use Ocdla\Member;

function password_menu()
{
	$items = array();

	$items['password-reset'] = array(
		'title' => 'Password Reset',
		'access' => true,
		'page callback' => 'requestReset',
		'files' => array(
			'includes/PasswordController.php'
		),
		'routeClass' => 'PasswordController'
	);
	
	$items['password-reset/%secure'] = array(
		'title' => 'Password Reset',
		'access' => true,
		'page callback' => 'resetPassword',
		'routeClass' => 'PasswordController',
			// pass the %secure token as the only argument
		'routeArguments' => array(1),
		'files' => array(
			'includes/PasswordController.php'
		),
	);
	
	
	$items['password-is-reset'] = array(
		'title' => 'Success!',
		'access' => true,
		'page callback' => 'passwordResetSuccess',
		'files' => array(
			'includes/PasswordController.php'
		),
		'routeClass' => 'PasswordController'
	);
	
	return $items;
}