<?php

use Clickpdx\OAuth\OAuthGrantTypes;
use Clickpdx\SfRestApiRequestTypes;
use Clickpdx\Http\HttpRequest;
use Clickpdx\ResourceLoader;


function sso_menu() {
	$items = array();
	
	$items['generatesession'] = array(
		'title' => 'SSO Session Generator',
		'comment' => 'Should be able to return a 302 response to the user-agent with the appropriate cookie attached.',
		'page callback' => 'generateSession',
		'theme' => 'ocdla2',
		'routeClass' => 'SsoController',
		// 'routeArguments' => array(2),
		'files' => array(
			'dependency1' => '/sites/default/modules/salesforce/includes/SalesforceController.php',
			'dependency2' => '/sites/default/modules/sso/includes/DefaultController.php',
			'controller' => 'includes/SsoController.php'
		)	
	);
	
	$items['logout'] = array(
		'title' => 'SSO logout',
		'comment' => 'Logout of the SAML and destroy session.',
		'page callback' => 'doLogout',
		'routeClass' => 'SsoController',
		'files' => array(
			'dependency1' => '/sites/default/modules/salesforce/includes/SalesforceController.php',
			'dependency2' => '/sites/default/modules/sso/includes/DefaultController.php',
			'controller' => 'includes/SsoController.php'
		)	
	);
	
	
	
	return $items;
}