logout_session_ams:
   path:     /logoutAms
   defaults: { _controller: OcdlaLoginBundle:Default:logoutAms }
   methods:     [GET]
generate_session:
   path:     /sso/sess
   defaults: { _controller: OcdlaLoginBundle:Default:phpsession }
   methods:     [GET]
ocdla_login_homepage:
   path:     /login
   defaults: { _controller: OcdlaLoginBundle:Default:index }
   methods:     [GET]
process_login:
   path:       /login
   methods:     [POST]
   defaults: { _controller: OcdlaLoginBundle:Default:processLogin }